// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "architecture/conventions.mdx": () => import("../content/docs/architecture/conventions.mdx?collection=docs"), "architecture/index.mdx": () => import("../content/docs/architecture/index.mdx?collection=docs"), "architecture/packages.mdx": () => import("../content/docs/architecture/packages.mdx?collection=docs"), "context/index.mdx": () => import("../content/docs/context/index.mdx?collection=docs"), "desktop/index.mdx": () => import("../content/docs/desktop/index.mdx?collection=docs"), "cli/agents.mdx": () => import("../content/docs/cli/agents.mdx?collection=docs"), "cli/commands.mdx": () => import("../content/docs/cli/commands.mdx?collection=docs"), "cli/extensions.mdx": () => import("../content/docs/cli/extensions.mdx?collection=docs"), "cli/index.mdx": () => import("../content/docs/cli/index.mdx?collection=docs"), "cli/kata-workflow.mdx": () => import("../content/docs/cli/kata-workflow.mdx?collection=docs"), "cli/preferences.mdx": () => import("../content/docs/cli/preferences.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/quickstart.mdx": () => import("../content/docs/getting-started/quickstart.mdx?collection=docs"), "orchestrator/index.mdx": () => import("../content/docs/orchestrator/index.mdx?collection=docs"), "symphony/backends.mdx": () => import("../content/docs/symphony/backends.mdx?collection=docs"), "symphony/configuration.mdx": () => import("../content/docs/symphony/configuration.mdx?collection=docs"), "symphony/deployment.mdx": () => import("../content/docs/symphony/deployment.mdx?collection=docs"), "symphony/index.mdx": () => import("../content/docs/symphony/index.mdx?collection=docs"), "symphony/monitoring.mdx": () => import("../content/docs/symphony/monitoring.mdx?collection=docs"), "symphony/notifications.mdx": () => import("../content/docs/symphony/notifications.mdx?collection=docs"), "symphony/prompts.mdx": () => import("../content/docs/symphony/prompts.mdx?collection=docs"), "visual-explainers/index.mdx": () => import("../content/docs/visual-explainers/index.mdx?collection=docs"), }),
};
export default browserCollections;