#!/bin/bash
#
# fetch-issues.sh
# Fetches open issues from upstream GitHub repo and generates ISSUES.md
#
# Usage: ./script/fetch-issues.sh [owner/repo]
# Default: gannonh/kata
#
# Requires: gh CLI (authenticated)

set -euo pipefail

REPO="${1:-gannonh/kata}"
OUTPUT_FILE=".planning/ISSUES.md"

# Ensure .planning directory exists
mkdir -p .planning

echo "Fetching open issues from $REPO..."

# Check if gh CLI is available
if ! command -v gh &> /dev/null; then
    echo "Error: GitHub CLI (gh) is required but not installed."
    echo "Install: https://cli.github.com/"
    exit 1
fi

# Check if authenticated
if ! gh auth status &> /dev/null; then
    echo "Error: Not authenticated with GitHub CLI."
    echo "Run: gh auth login"
    exit 1
fi

# Fetch issues as JSON
ISSUES_JSON=$(gh issue list --repo "$REPO" --state open --limit 100 --json number,title,url,labels,author,createdAt,updatedAt,comments)

# Count issues
ISSUE_COUNT=$(echo "$ISSUES_JSON" | jq 'length')

# Generate markdown
cat > "$OUTPUT_FILE" << EOF
# Open Issues

Upstream: [$REPO](https://github.com/$REPO/issues)
Generated: $(date -u +"%Y-%m-%d %H:%M UTC")
Total: $ISSUE_COUNT open issues

---

EOF

# Categorize and format issues
echo "## 🐛 Bugs" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "$ISSUES_JSON" | jq -r '
  .[] | 
  select(
    (.title | test("bug|error|fix|broken|issue|fail"; "i")) or
    (.labels | map(.name) | any(test("bug"; "i")))
  ) |
  "| [#\(.number)](\(.url)) | \(.title) | @\(.author.login) | \(.createdAt | split("T")[0]) |"
' | {
    echo "| Issue | Title | Author | Created |"
    echo "|-------|-------|--------|---------|"
    cat
} >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "## ✨ Feature Requests" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "$ISSUES_JSON" | jq -r '
  .[] | 
  select(
    (.title | test("feature|request|add|support|proposal"; "i")) or
    (.labels | map(.name) | any(test("feature|enhancement"; "i")))
  ) |
  "| [#\(.number)](\(.url)) | \(.title) | @\(.author.login) | \(.createdAt | split("T")[0]) |"
' | {
    echo "| Issue | Title | Author | Created |"
    echo "|-------|-------|--------|---------|"
    cat
} >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "## 💬 Discussions" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "$ISSUES_JSON" | jq -r '
  .[] | 
  select(
    (.title | test("discussion|question|how"; "i")) or
    (.labels | map(.name) | any(test("question|discussion"; "i")))
  ) |
  "| [#\(.number)](\(.url)) | \(.title) | @\(.author.login) | \(.createdAt | split("T")[0]) |"
' | {
    echo "| Issue | Title | Author | Created |"
    echo "|-------|-------|--------|---------|"
    cat
} >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "## 📋 All Issues (by update date)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "$ISSUES_JSON" | jq -r '
  sort_by(.updatedAt) | reverse | .[] |
  "| [#\(.number)](\(.url)) | \(.title) | @\(.author.login) | \(.updatedAt | split("T")[0]) | \(.comments | length) |"
' | {
    echo "| Issue | Title | Author | Updated | Comments |"
    echo "|-------|-------|--------|---------|----------|"
    cat
} >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "*Generated by \`script/fetch-issues.sh\`*" >> "$OUTPUT_FILE"

echo "✓ Generated $OUTPUT_FILE with $ISSUE_COUNT issues"
