// @generated - DO NOT EDIT
// This file is auto-generated by the build system

export interface GeneratedType {
  id: string;
  name: string;
}

export const GENERATED_CONSTANT = 'should-not-appear-in-index';

export function generatedHelper(): void {
  // no-op
}
